# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  finger_L_joint:
    has_velocity_limits: true
    max_velocity: 6.159937255
    has_acceleration_limits: false
    max_acceleration: 0
  finger_R_joint:
    has_velocity_limits: true
    max_velocity: 6.159937255
    has_acceleration_limits: false
    max_acceleration: 0
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.14159265358979
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.87979326579064
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3:
    has_velocity_limits: true
    max_velocity: 3.45575191894877
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4:
    has_velocity_limits: true
    max_velocity: 4.31968989868597
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5:
    has_velocity_limits: true
    max_velocity: 4.31968989868597
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6:
    has_velocity_limits: true
    max_velocity: 6.91150383789755
    has_acceleration_limits: false
    max_acceleration: 0
  finger_3rd_joint:
    has_velocity_limits: true
    max_velocity: 6.159937255
    has_acceleration_limits: false
    max_acceleration: 0
